blank_issues_enabled: false
contact_links:
  - name: PimaxXR Homepage
    url: https://github.com/mbucchia/Pimax-OpenXR/wiki
    about: The homepage has a lot of useful information, including Compatibility list.
  - name: OpenComposite Homepage
    url: https://gitlab.com/znixian/OpenOVR/-/tree/openxr
    about: If your questions/issues are with OpenComposite and not PimaxXR, head to their homepage for information.
  - name: OpenComposite Discord
    url: https://discord.gg/sQ2jwSb62J
    about: If your questions/issues are with OpenComposite and not PimaxXR, use their Discord.
  - name: OpenXR Toolkit Homepage
    url: https://mbucchia.github.io/OpenXR-Toolkit/
    about: The homepage has A LOT OF INFORMATION if you are using OpenXR Toolkit. Check there first for the answer to your questions/issues. There is a Search bar at the top.
  - name: OpenXR Toolkit/PimaxXR Discord
    url: https://discord.gg/NxvH3x66js
    about: Finally, if you have checked all the information above, but still cannot address your questions/issues, ask and answer questions on our Discord.
